// lib/data/models/symptom_report_model.dart
// Data model for villager symptom reports.
// Supports both Firestore serialization and Hive offline storage.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive/hive.dart';

part 'symptom_report_model.g.dart'; // generated by hive_generator

/// Represents a disease symptom report filed by a villager.
@HiveType(typeId: 0)
class SymptomReportModel extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String reporterId;       // UID of reporting user

  @HiveField(2)
  final String reporterName;

  @HiveField(3)
  final String village;

  @HiveField(4)
  final String district;

  @HiveField(5)
  final String state;

  @HiveField(6)
  final List<String> symptoms;   // Selected symptoms list

  @HiveField(7)
  final int affectedCount;       // Number of people affected

  @HiveField(8)
  final String? photoUrl;        // Firebase Storage URL (nullable)

  @HiveField(9)
  final String? additionalNotes;

  @HiveField(10)
  final DateTime reportedAt;

  @HiveField(11)
  final bool isSynced;           // false = stored offline, not yet uploaded

  @HiveField(12)
  final String status;           // pending | reviewed | resolved

  @HiveField(13)
  final double? latitude;

  @HiveField(14)
  final double? longitude;

  SymptomReportModel({
    required this.id,
    required this.reporterId,
    required this.reporterName,
    required this.village,
    required this.district,
    required this.state,
    required this.symptoms,
    required this.affectedCount,
    this.photoUrl,
    this.additionalNotes,
    required this.reportedAt,
    this.isSynced = false,
    this.status = 'pending',
    this.latitude,
    this.longitude,
  });

  /// Convert to Firestore map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'reporterId': reporterId,
      'reporterName': reporterName,
      'village': village,
      'district': district,
      'state': state,
      'symptoms': symptoms,
      'affectedCount': affectedCount,
      'photoUrl': photoUrl,
      'additionalNotes': additionalNotes,
      'reportedAt': Timestamp.fromDate(reportedAt),
      'status': status,
      'location': (latitude != null && longitude != null)
          ? GeoPoint(latitude!, longitude!)
          : null,
    };
  }

  /// Create from Firestore document
  factory SymptomReportModel.fromMap(Map<String, dynamic> map) {
    GeoPoint? geo = map['location'];
    return SymptomReportModel(
      id: map['id'] ?? '',
      reporterId: map['reporterId'] ?? '',
      reporterName: map['reporterName'] ?? '',
      village: map['village'] ?? '',
      district: map['district'] ?? '',
      state: map['state'] ?? '',
      symptoms: List<String>.from(map['symptoms'] ?? []),
      affectedCount: map['affectedCount'] ?? 1,
      photoUrl: map['photoUrl'],
      additionalNotes: map['additionalNotes'],
      reportedAt:
          (map['reportedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isSynced: true,
      status: map['status'] ?? 'pending',
      latitude: geo?.latitude,
      longitude: geo?.longitude,
    );
  }

  /// Return a copy marked as synced
  SymptomReportModel withSynced() {
    return SymptomReportModel(
      id: id,
      reporterId: reporterId,
      reporterName: reporterName,
      village: village,
      district: district,
      state: state,
      symptoms: symptoms,
      affectedCount: affectedCount,
      photoUrl: photoUrl,
      additionalNotes: additionalNotes,
      reportedAt: reportedAt,
      isSynced: true,
      status: status,
      latitude: latitude,
      longitude: longitude,
    );
  }

  @override
  String toString() =>
      'SymptomReport(id: $id, village: $village, symptoms: $symptoms, '
      'affected: $affectedCount, synced: $isSynced)';
}
